name: ghp-deploy

on:
 push:
  branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
         npm ci
         npm run build
         pip install ghp-import
         ghp-import -n ./dist
         git push -qf https://github.com/c12i/pixie.git gh-pages
