name: ghp-deploy

on:
 push:
  branches:
    - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: |
          npm ci
          npm run build
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/c12i/pixie.git
          npx gh-pages -d ./dist -u "github-actions-bot <support+actions@github.com>" --cname pixie.collinsmuriuki.xyz
